name: MSAdoc Workflow

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install the MSAdoc CLI
        run: npm install -g msadoc-cli@latest

      - name: Upload the Service Doc
        run: msadoc upload ./msadoc.json --server=$MSADOC_SERVER_URL
        env:
          MSADOC_SERVER_URL: ${{ secrets.MSADOC_SERVER_URL }}
          MSADOC_API_KEY: ${{ secrets.MSADOC_API_KEY }}
